auth_email=""                   # The email used to login 'https://dash.cloudflare.com'
auth_method="token"             # Set to "global" for Global API Key or "token" for Scoped API Token
auth_key=""                     # Your API Token or Global API Key
zone_identifier=""              # Can be found in the "Overview" tab of your domain
record_name="home.antran22.xyz" # Which record you want to be synced. Full name $subdomain.$domain is needed
ttl="1"                         # Set the DNS TTL (seconds). 1 means automatic
proxy="false"                   # Set the proxy to true or false
sitename="Home Server"          # Title of site "Example Site"
shoutrrr_url=""
